name: Elastic Beanstalk Logs

on:
  workflow_call:
  workflow_dispatch:

jobs:
  eb-logs:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        {% raw %}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        {% endraw %}
    - name: Print last 100 EB events
      run: |
        aws elasticbeanstalk describe-events \
          --environment-name {{ cookiecutter.eb_environment }} \
          --max-items 100 \
          --query 'Events[].{Date:EventDate,Severity:Severity,Message:Message}' \
          --output table
